### ISSUE TITLE
Register function

### ISSUE THREAD

**Issue by isakskold** [Jaerker/mindMastersAgile#35]
## Hur viktig: 

# Acceptans kriterier: 
- [x] Lägg till funktion för registrering
> - [x] kolla om användarnamn redan finns med i user-listan/ lösenorden inte stämmer överens
> - [x] OM allt stämmer, spara användaren i user-listan
> - [ ] Kör funktionen "login" och därefter visa ett meddelande att det lyckades

**Comment by isakskold** [comment]
Får problem med inloggfunktionen i samband med att registrera användare. Att byta formulärs vy triggar inloggning medans logga in knappen ger felmeddelande om jag försöker logga in en användare från local storage jag har registrerat. Försöker jag logga in en default användare som "jesper123" blir hela skärmen vit. Här funkar det dock också att logga in jesper123 genom att byta formulärsvy.

Jag avvaktar med att implementera inlogg funktionen till registrera funktionen tills dessa problem är lösta.

**Comment by Jaerker** [comment]
@isakskold Är det något du behöver, eller är det något som inte fungerar?

Kan vara att din branch inte är uppdaterad, med tanke på att den varit igång ett tag. Med tanke på att api.js filen fungerar bra så borde man kunna koppla på `api.user.login(username)` om man loggar in korrekt, eller `api.user.add(userToAdd)` när man ska lägga till någon i listan av användare, förutsatt att alla checkar är gjorda.
 
Testa i värsta fall att hämta hem api.js filen från dev branchen och lägg den i `scripts/` mappen, importera och kör.
